title: DataTyper Docs
description: Official documentation for the DataTyper Figma plugin

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

# Dark theme
color_scheme: dark
enable_dark_mode: true

search_enabled: true
heading_anchors: true